# Generated by Django 3.0.6 on 2020-05-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0003_auto_20200529_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookfor',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
