# Generated by Django 3.0.6 on 2020-05-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0005_auto_20200529_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='lookfor',
            field=models.ManyToManyField(related_name='participants', to='timelines.UserExtend'),
        ),
        migrations.DeleteModel(
            name='LookFor',
        ),
    ]
