# Generated by Django 3.0.6 on 2020-05-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0006_auto_20200529_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='lookfor',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='user',
        ),
        migrations.AddField(
            model_name='userextend',
            name='join',
            field=models.ManyToManyField(related_name='participants', to='timelines.Content'),
        ),
    ]
