# Generated by Django 3.0.6 on 2020-05-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0007_auto_20200529_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='name',
            field=models.CharField(default='guest', max_length=20),
            preserve_default=False,
        ),
    ]
