# Generated by Django 3.0.6 on 2020-05-29 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0008_userextend_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='join',
        ),
        migrations.RemoveField(
            model_name='userextend',
            name='name',
        ),
        migrations.AddField(
            model_name='userextend',
            name='phone',
            field=models.CharField(default='081297930xxx', max_length=15),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join', models.ManyToManyField(related_name='participants', to='timelines.Content')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
