# Generated by Django 3.0.6 on 2020-05-30 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0011_auto_20200530_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatepost',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
