# Generated by Django 3.0.6 on 2020-05-30 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0013_auto_20200530_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
