# Generated by Django 3.0.6 on 2020-05-30 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0014_content_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='held_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='max_participants',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
