# Generated by Django 3.0.6 on 2020-06-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0015_auto_20200530_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtend',
        ),
    ]
