# Generated by Django 3.0.6 on 2020-07-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0019_collaborationpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationpost',
            name='category',
            field=models.CharField(default='competition', max_length=50),
            preserve_default=False,
        ),
    ]
