# Generated by Django 3.0.6 on 2020-07-13 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelines', '0021_auto_20200713_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationpost',
            name='colabs_join',
            field=models.ManyToManyField(blank=True, related_name='joined_colabs', to=settings.AUTH_USER_MODEL),
        ),
    ]
