# Generated by Django 3.0.6 on 2020-07-14 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0023_auto_20200714_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='held_on',
            new_name='held_on_end',
        ),
        migrations.AddField(
            model_name='content',
            name='held_on_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
