# Generated by Django 3.0.6 on 2020-07-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0024_auto_20200714_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='terms',
            field=models.TextField(default='aaa zz', max_length=1000),
            preserve_default=False,
        ),
    ]
