# Generated by Django 3.0.6 on 2020-07-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0026_auto_20200715_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='contentImage',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
