# Generated by Django 3.0.6 on 2020-07-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelines', '0029_auto_20200715_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='teams',
        ),
        migrations.AddField(
            model_name='content',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='for_joined', to='timelines.CollaborationPost'),
        ),
    ]
