# Generated by Django 3.0.6 on 2020-07-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userextend'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextend',
            name='profileImg',
            field=models.ImageField(blank=True, upload_to='galery'),
        ),
    ]
